export const GROUPID_1 = 'Appearance'
export const GROUPID_2 = 'Behavior'
export const GROUPID_3 = 'Font'
export const GROUPID_4 = 'Misc'
export const GROUPID_5 = 'Picture'
export const GROUPID_6 = 'Position'
export const GROUPID_7 = 'Scrolling'
export const GROUPID_8 = 'Data'
