export const ComboBox = {
  properties: {
    AutoSize: false,
    AutoTab: false,
    AutoWordSelect: true,
    BackColor: '#ffffff',
    BackStyle: 1,
    BorderColor: '#ffffff',
    BorderStyle: 1,
    BoundColumn: 3,
    ColumnCount: 3,
    ColumnHeads: false,
    ColumnWidths: '30pt;50pt;100pt',
    ControlSource: 'd8',
    ControlTipText: 'helptext',
    DragBehavior: 0,
    DropButtonStyle: 1,
    Enabled: true,
    EnterFieldBehavior: 0,
    Font: {
      FontName: 'Arial',
      FontSize: 10,
      FontBold: false,
      FontItalic: true,
      FontUnderline: true,
      FontStrikethrough: true,
      FontStyle: 'Arial Narrow Italic'
    },
    ForeColor: '#000000',
    Height: 18,
    HelpContextID: 0,
    HideSelection: true,
    IMEMode: 0,
    Left: 0,
    ListRows: 4,
    ListStyle: 0,
    ListWidth: '0 pt',
    Locked: false,
    MatchEntry: 1,
    MatchRequired: false,
    MaxLength: 0,
    MouseIcon: '',
    MousePointer: 0,
    Name: 'ComboBox',
    ID: 'ID_ComboBox1',
    RowSource: 'a1:c9',
    SelectionMargin: true,
    SpecialEffect: 0,
    style: 0,
    TabIndex: 0,
    TabStop: true,
    Tag: '',
    Text: 's',
    TextAlign: 1,
    TextColumn: 2,
    Top: 0,
    TopIndex: 2,
    Value: 'c3',
    Visible: true,
    Width: 72
  },
  controls: [],
  extraDatas: {
    // it can be different from value
    ControlSourceValue: 'c3',
    ColumnHeadsValues: ['column1', 'column2', 'column3'],
    RowSourceData: [
      ['a', 'k', 'a1'],
      ['b', 'b', 'b2'],
      ['c', 's', 'c3'],
      ['d', 'a', 'd4'],
      ['e', 'd', 'e5'],
      ['f', 'wef', 'f6'],
      ['g', 'awe', 'g7'],
      ['h', 'rty', 'h8'],
      ['i', 'qqq', 'i9']
    ]
  },
  type: 'ComboBox'
}
